objects = 1 2

include ../commonFunction.md

include ../commonMakefile

# .PHONY: all insert updateExpect clean

# all: insert

# compileAbstract:
# 	@ $(call compileAbstractTemplate)

# compileDetail:
# 	@ $(call compileDetailTemplate)

# runAbstract:
# 	@ $(call runAbstractTemplate, 1 2)

# runDetail:
# 	@ $(call runDetailTemplate, 1 2)

# testAbstract:
# 	@ $(call testAbstractTemplate, 1 2)

# testDetail:
# 	@ $(call testDetailTemplate, 1 2)

# checkMemoryAbstract:
# 	@ $(call checkMemoryAbstractTemplate, 1 2)

# checkMemoryDetail:
# 	@ $(call checkMemoryDetailTemplate, 1 2)

# clean:
# 	@ $(call cleanTemplate)

# updateExpect:
# 	@ $(call updateExpectTemplate, 1 2, '.')
